#
# -------------------------- #
# Filter Properties Database #
#                            #
# $Id$                       #
# -------------------------- #
#
#
# Filter Clear-03 - no filter
#
filter.Clear-03.description 		=No Filter
filter.Clear-03.skybright		=0.0
filter.Clear-03.skydark			=0.0
filter.Clear-03.zero			=0.0
filter.Clear-03.width			=0.0
filter.Clear-03.center			=0.0
filter.Clear-03.qfilter			=0.0
filter.Clear-03.qccd			=0.0
filter.Clear-03.physical_thickness	=0.0
filter.Clear-03.optical_thickness	=0.0
#
# Filter  SDSS-U-03 - Sloan U
#
filter.SDSS-U-03.description 		=Sloan U 
filter.SDSS-U-03.skybright		=17.4
filter.SDSS-U-03.skydark		=21.0
filter.SDSS-U-03.zero			=4.4e-9
filter.SDSS-U-03.width			=531
filter.SDSS-U-03.center			=3530
filter.SDSS-U-03.qfilter		=0.5
filter.SDSS-U-03.qccd			=0.5
filter.SDSS-U-03.physical_thickness	=0.0
filter.SDSS-U-03.optical_thickness	=0.0
#
# Filter SDSS-G-03
#
filter.SDSS-G-03.description 		=Sloan G
filter.SDSS-G-03.skybright		=17.5
filter.SDSS-G-03.skydark		=21.7
filter.SDSS-G-03.zero			=5.0e-9
filter.SDSS-G-03.width			=1332
filter.SDSS-G-03.center			=4820
filter.SDSS-G-03.qfilter		=0.85
filter.SDSS-G-03.qccd			=0.83	
filter.SDSS-G-03.physical_thickness	=0.0
filter.SDSS-G-03.optical_thickness	=0.0
#
# Filter SDSS-R-03
#
filter.SDSS-R-03.description 		=Sloan R
filter.SDSS-R-03.skybright		=17.7
filter.SDSS-R-03.skydark		=20.4
filter.SDSS-R-03.zero			=1.7e-9
filter.SDSS-R-03.width			=1410
filter.SDSS-R-03.center			=6252
filter.SDSS-R-03.qfilter		=0.85
filter.SDSS-R-03.qccd 			=0.75
filter.SDSS-R-03.physical_thickness	=0.0
filter.SDSS-R-03.optical_thickness	=0.0
#
# Filter SDSS-I-03
#
filter.SDSS-I-03.description 		=Sloan I
filter.SDSS-I-03.skybright		=17.3
filter.SDSS-I-03.skydark		=19.3
filter.SDSS-I-03.zero			=0.9e-9
filter.SDSS-I-03.width			=1770
filter.SDSS-I-03.center			=7782
filter.SDSS-I-03.qfilter		=0.85
filter.SDSS-I-03.qccd			=0.52	
filter.SDSS-I-03.physical_thickness	=0.0
filter.SDSS-I-03.optical_thickness	=0.0
#
# Filter SDSS-Z-03
#
filter.SDSS-Z-03.description 		=Sloan Z
filter.SDSS-Z-03.skybright		=17.3
filter.SDSS-Z-03.skydark		=18.3
filter.SDSS-Z-03.zero			=0.7e-9
filter.SDSS-Z-03.width			=1500
filter.SDSS-Z-03.center			=9000
filter.SDSS-Z-03.qfilter		=0.95
filter.SDSS-Z-03.qccd			=0.26 
filter.SDSS-Z-03.physical_thickness	=0.0
filter.SDSS-Z-03.optical_thickness	=0.0
#
# Filter SDSS-Y-03
#
filter.SDSS-Y-03.description 		=Sloan Y
filter.SDSS-Y-03.skybright		=0.0
filter.SDSS-Y-03.skydark		=0.0
filter.SDSS-Y-03.zero			=0.0
filter.SDSS-Y-03.width			=0.0
filter.SDSS-Y-03.center			=10000
filter.SDSS-Y-03.qfilter		=0.0
filter.SDSS-Y-03.qccd			=0.0 
filter.SDSS-Y-03.physical_thickness	=0.0
filter.SDSS-Y-03.optical_thickness	=0.0
